spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: '{cipher}6413a888f36fe53fb0611cd2fefa06c3c74ed24e3bb558cb2d09aef5e8916b6c'


token:
  expiration_time: 864000000
  secret: user_token


gateway:
  ip: 127.0.0.1

order_service:
  url: http://order-service/order-service/%s/orders

  exception:
    order_is_empty: User's orders is empty